### LAMBDA

In [1]:
#lambda f'n can take any no of arguments.
#Can return just 1 value in the form  of expressions.
#definition does not have an explicit return stataement but it always contains contains an expression which is return.
#a 1 line version of f'n cannot access variables other than those in their parameter
#functions cannot access global variables
#can pass lambda f'n as arguments to a function
# It decomposes a problem into a set of functions

In [2]:
a=lambda x:x*2
print(a(10))

20


In [3]:
print((lambda x:x*2)(9))

18


### FILTER

In [4]:
l=[10,4,5,2,6]
print(list(filter(lambda x: x%2==0,l)))

[10, 4, 2, 6]


In [5]:
# Constructs a list from those elements of a list for which the f'n return
# f'n returns a sequence that contains items from the sequence for which f'n is stored

### MAP

In [6]:
# f'n must have as many args as there are sequences
# Each argument is called with the corresponding item from each seqquence or none if one squence is shorter than another
l=[10,4,5,2,6]
print(list(map(lambda x:x*5,l)))

[50, 20, 25, 10, 30]


### REDUCE

In [9]:
# it returns a single value generated by calling a f'n on the first 2 items of the sequence and then on the result and then the next item and so on
# if there is only one item in the sequence then its value is returned
# if the sequence is empty an excetion is raised
# Creating a list is very extensive range . Will generate a memory error or overflow error
from functools import reduce
l=[2,3,4,5]
print(reduce(lambda x,y: x+y,l))


14


In [12]:
# using map wap taking i/p of 3 sequences
#1-return sum of first 2
#2- return product of 1st and 3rd
#3-difference in elements of 2nd and 3rd  sequence
a=[1,2,3,4]
b=[5,6,7,8]
c=[9,10,11,12]
print(list(map(lambda x,y: x+y,a,b)))
print(list(map(lambda x,y: x*y,a,c)))
print(list(map(lambda x,y: x-y,b,c)))



[6, 8, 10, 12]
[9, 20, 33, 48]
[-4, -4, -4, -4]


In [25]:
# wap that createss a list of no's from 1 to 20 that are either divisble by 2 or 4 using filter f'n

print(list(filter(lambda x:x%2==0 or x%4==0,[int(input()) for i in range(5)])))

1
2
2
3
4
[2, 2, 4]


In [31]:
# wap to remove all the duplicates from a list
# wap tht has a list of all pos and neg no. create another list using filter that has pos.
# wap that converts a string of all uppercase chars into string of lowercase chars using map
# wap to find largest value in a list using reduce f'n.
# Given a list of strings , find all the palindromes
a=[int(input()) for i in range(5)]
print(list(filter(lambda x:a[a.index(x)] in a[:a.index(x)]==True,a)))

1
2
2
3
4
[]


In [3]:
c=[9,10,11,12]
print(19 not in c)

True


In [5]:
#wap to count the repeated no's in a list
def fu(l):
    c=0
    a=[]
    for i in range(len(l)):
        if l[i] in l[i+1:] and l[i] not in a:
            c+=1
            a.append(l[i])
    return c
a=[int(input()) for i in range(int(input()))]
print(fu(a))
        

5
1
17
22
17
23
1


In [6]:
a,b,c,d=int(input()),int(input()),int(input()),int(input())
print(d==(a**2+b**2+c**2))


2
3
4
29
True


### You are given astring and have to validate whether they are valid mobile no's or not. A valid monile no is a 10 digit no starting with 7,8,9.The first line contains an int n which is the no of inputs.The n following lines contains some strings.1>n<10.

In [4]:
import re
def number(n):
    regex='[789]\d{9}'
    if re.findall(regex,n):
        print('yes')
    else:
        print('no')
q=int(input('enter N'))
for i in range(0,q):
    w=input('enter no')
    number(w)
            

enter N1
enter no9999999999
yes


### A valid email add meets the following criteria. It is composed of user name, domain name assembled in the form usernsame@domain.extension.The username starts with english alphabetic character and any subsequent characters consist of one or more of the following: -,._  The domain and extension contains inly english alphabetical characters.The extension is 1,2 or 3 characters in length. Given n pair of names nd email add as inputs. Print each name and the emai pair having valid email on new line

In [5]:
import re
def number(n):
    regex='\w+[-, ]+@[a-zA-Z]+.\D{3}'
    if re.findall(regex,n):
        print('yes')
    else:
        print('no')
q=int(input('Enter'))
for i in range(0,q):
    w=input("Enter email")
    number(w)

Enter1
Enter emailarun-@hotmail.in
yes


In [8]:
a=[int(input()) for i in range(int(input()))]
b=[int(input()) for i in range(int(input()))]
c=a+b
for i in range(len(c)):
    
    for j in range(len(c)-i-1):
        if c[j]>c[j+1]:
            c[j],c[j+1]=c[j+1],c[j]
print(c)

1
1
1
1
[1, 1]


In [11]:
def rot(a):
    t=a[0]
    for i in range(len(a)-1):
        a[i]=a[i+1]
    a[len(a)-1]=t
def times(a,k):
    for i in range(k):
        rot(a)
a=[1,2,3,4]
times(a,2)
print(a)

[3, 4, 1, 2]


In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
b=a.T
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
[[1 4 6]
 [2 5 7]
 [3 6 8]]


In [ ]:
a=[1,3,5,6,19,49,51,31,21,9,15]
dim=(int(input()))k

In [1]:
#sum of digits
def digital_root(n):
    return n if n < 10 else digital_root(sum(map(int,str(n))))

In [2]:
#convert string to camel case
def to_camel_case(text):
    removed = text.replace('-', ' ').replace('_', ' ').split()
    if len(removed) == 0:
        return ''
    return removed[0]+ ''.join([x.capitalize() for x in removed[1:]])

In [3]:
#Delete occurrences of an element if it occurs more than n times
def delete_nth(order,max_e):
    ans = []
    for o in order:
        if ans.count(o) < max_e: ans.append(o)
    return ans

### Merge Sort

In [3]:
a=[int(input()) for i in range(int(input("Enter no of elements")))]
l=len(a)
def merge(a,start,end):
    if start<end:
        mid=(start+end)//2
        merge(a,start,mid)
        merge(a,mid+1,end)
        merging(a,start,end)
def merging(a,start,end):
    p=start
    mid=(start+end)//2
    q=mid
    f=[]
    j=0
    while(p<mid and q<end):
        if a[p]<a[q]:
            f.append(a[p])
            p+=1
        else:
            f.append(a[q])
            q+=1
    while(p<mid):
        f.append(a[p])
        p+=1
    while(q<end):
        f.append(a[q])
        q+=1
    for i in range(len(f)):
        a[start+i]=f[i]
merge(a,0,l)
print("The sorted list is \n",a)

Enter no of elements6
3
1
5
2
6
4
The sorted list is 
 [1, 2, 3, 4, 5, 6]


### Quick Sort

In [6]:
a=[int(input()) for i in range(int(input("Enter no of elements")))]
l=len(a)
def quickSort(a,start,end):
    if start<end:
        pp=partition(a,start,end)
        quickSort(a,start,pp-1)
        quickSort(a,pp+1,end)
def partition(a,start,end):
    pivot=a[start]
    count,i = 0,start+1
    while(i!=end+1):
        if a[i]<pivot:
            count+=1
        i+=1
    pi=start+count
    a[pi],a[start]=a[start],a[pi]
    i,j = start,end
    while i<j:
        while i<=end and a[i]<=pivot:
            i+=1
        while a[j]>pivot:
            j-=1
        if i<=j:
            a[i],a[j]=a[j],a[i]
            i+=1
            j-=1
    return pi
quickSort(a,0,l-1)
print("The sorted list is \n",a)

Enter no of elements6
3
5
1
4
2
6
The sorted list is 
 [1, 2, 3, 4, 5, 6]


### Binary Search

In [2]:
a=[int(input("Enter element")) for i in range(int(input("Enter no of elements--in sorted order")))]
val=int(input("Enter value to search"))
def binsort(a,val):
    n=len(a)
    front=0
    back=n-1
    if val<a[front] or val>a[back]:
        return -1
    while front<=back:
        mid=(front+back)//2
        if val==a[mid]:
            return mid
        elif val>a[mid]:
            front=mid+1
        else:
            back=mid-1
    return -1
index=binsort(a,val)
print("The index is    ",index)

Enter no of elements--in sorted order5
Enter element1
Enter element3
Enter element5
Enter element7
Enter element9
Enter value to search7
The index is     3


### Selection Sort

In [1]:
a=[int(input("Enter element")) for i in range(int(input("Enter no of elements")))]
def selsort(a):
    for i in range(len(a)-1):
        minn=a[i]
        minix=i
        for j in range(i+1,len(a)):
            if minn>a[j]:
                minn=a[j]
                minix=j
        if minix!=i:
            a[i],a[minix]=a[minix],a[i]
    print(a)
selsort(a)


Enter no of elements5
Enter element3
Enter element1
Enter element4
Enter element2
Enter element6
[1, 2, 3, 4, 6]
